import {
  eventDefinitionCatalogSchema,
  type EventCandidate,
  type EventCategory,
  type EventDefinition,
} from "@roommates/shared";

const ALL_CHARACTER_CHOICES = ["ACCEPT", "MODIFY", "DECLINE", "IGNORE", "INITIATE"] as const;

const definitions = [
  {
    id: "observe-rest",
    title: "何も提案せず見守る",
    category: "rest",
    intimacyTier: 0,
    allowedPhases: ["morning", "afternoon", "evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 0, max: 2 },
    location: "任意の落ち着ける場所",
    durationMinutes: 30,
    preconditions: {},
    producerControls: ["見守る時間", "休息できる場所"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 8,
      stress: 8,
      affection: 2,
      trust: 2,
      romanticAwareness: 1,
    },
    cooldownPhases: 0,
    maxUsesPerDay: 4,
    maxUsesPerRun: 28,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人が同じ空間を選んだ場合も、会話や交流を義務づけず静かに過ごす。",
      oneParticipates: "休息を選んだ側だけが自分のペースを取り戻し、相手の状態は変えない。",
      bothDecline: "二人とも別の自発行動を選び、関係値を増減させない。",
      modified: "各自が休息の長さや場所を変え、安全な自発行動へ移る。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["ROOMMATESの常時利用可能な安全フォールバック。"],
    safetyNotes: [
      "何も起こさない選択を失敗として扱わない。",
      "一方の休息を他方への拒絶や信頼低下に変換しない。",
    ],
  },
  {
    id: "shared-cooking",
    title: "一緒に料理する",
    category: "cook",
    intimacyTier: 1,
    allowedPhases: ["morning", "afternoon", "evening"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "キッチン／ダイニング",
    durationMinutes: 45,
    preconditions: { minEnergy: 25, maxStress: 80 },
    producerControls: ["料理の種類", "難易度", "担当の決め方", "所要時間"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 8,
      stress: 6,
      affection: 8,
      trust: 8,
      romanticAwareness: 5,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人で安全な範囲の役割を分担し、完成度ではなく共同作業を記憶する。",
      oneParticipates: "参加する側だけが簡単な一品を作り、相手には参加や試食を求めない。",
      bothDecline: "調理を取りやめ、各自が軽食か休息を選ぶ。",
      modified: "品数、難易度、担当または時間を減らし、無理のない共同作業にする。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["共同目標を通じた低親密度イベントの基本形。"],
    safetyNotes: [
      "空腹、疲労、不得意さを責める展開にしない。",
      "危険な調理や食事制限に反する内容を生成しない。",
    ],
  },
  {
    id: "movie-night",
    title: "気軽な映画会",
    category: "movie",
    intimacyTier: 1,
    allowedPhases: ["evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング",
    durationMinutes: 90,
    preconditions: { minEnergy: 15, maxStress: 85 },
    producerControls: ["作品ジャンル", "上映時間", "飲み物", "照明"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 6,
      stress: 8,
      affection: 7,
      trust: 6,
      romanticAwareness: 6,
    },
    cooldownPhases: 3,
    maxUsesPerDay: 1,
    maxUsesPerRun: 3,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人が合意した作品を観て、感想を話すかどうかも各自が選ぶ。",
      oneParticipates: "観たい側だけが視聴し、相手は同席や感想を求められない。",
      bothDecline: "上映を見送り、短い休息か別々の自由時間へ移る。",
      modified: "短編へ変える、途中で止める、ジャンルを変えるなど負担を軽くする。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["同じ空間を共有しつつ会話を強制しない低圧イベント。"],
    safetyNotes: [
      "怖さやセンシティブな題材をサプライズとして押しつけない。",
      "夜更かしを強制せず、途中退出を不利益にしない。",
    ],
  },
  {
    id: "shared-cleaning",
    title: "共有スペースを整える",
    category: "clean",
    intimacyTier: 1,
    allowedPhases: ["morning", "afternoon", "evening"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／キッチン",
    durationMinutes: 40,
    preconditions: { minEnergy: 30, maxStress: 80 },
    producerControls: ["掃除する範囲", "担当", "時間上限", "BGM"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 8,
      stress: 8,
      affection: 5,
      trust: 9,
      romanticAwareness: 3,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "共有物だけを対象に役割分担し、生活習慣の違いは話し合って調整する。",
      oneParticipates: "参加する側が共有スペースの小範囲だけを整え、相手の私物には触れない。",
      bothDecline: "片付けを延期し、共有スペースの安全確保だけを行う。",
      modified: "範囲か時間を半分にし、互いの許容基準を一つだけ確認する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["共同生活の価値観を安全に可視化する共同目標イベント。"],
    safetyNotes: [
      "個室、端末、手紙など相手の私物を無断で扱わない。",
      "きれい好き度の違いを人格批判へ結びつけない。",
    ],
  },
  {
    id: "gentle-conversation",
    title: "答えなくてもよい会話",
    category: "talk",
    intimacyTier: 1,
    allowedPhases: ["afternoon", "evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／バルコニー",
    durationMinutes: 25,
    preconditions: { minEnergy: 15, maxStress: 85, minTrust: 20 },
    producerControls: ["許可済みの話題カテゴリ", "質問数", "場所", "飲み物"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 7,
      affection: 7,
      trust: 9,
      romanticAwareness: 7,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 2,
    maxUsesPerRun: 6,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "許可済みの軽い質問から一つ選び、回答、逆質問、パスを同価値の選択として扱う。",
      oneParticipates: "答えた側の自己紹介としてだけ記憶し、聞かなかった側の信頼は変えない。",
      bothDecline: "質問を撤回し、雑談または各自の休息へ移る。",
      modified: "質問を一段軽くする、選択式にする、または一問だけに短縮する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["質問カードや高親密度会話へ拡張できる基礎イベント。"],
    safetyNotes: [
      "パスを不参加、拒絶、嘘として評価しない。",
      "センシティブな自由文を質問として直接注入しない。",
    ],
  },
  {
    id: "targeted-apology",
    title: "一つの出来事について謝る",
    category: "apology",
    intimacyTier: 2,
    allowedPhases: ["afternoon", "evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "落ち着いて話せる共有スペース",
    durationMinutes: 25,
    preconditions: {
      minEnergy: 20,
      maxStress: 80,
      minTrust: 15,
      requiresConflict: true,
    },
    producerControls: ["対象にする既存の対立一件", "場所", "時間上限"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 10,
      affection: 6,
      trust: 10,
      romanticAwareness: 5,
    },
    cooldownPhases: 3,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "指定された既存の対立一件だけを話し、謝罪と受容を別々の選択として扱う。",
      oneParticipates: "参加する側が伝えたい内容を整理するだけに留め、対立は未解決のまま残す。",
      bothDecline: "対立を維持したまま会話を延期し、その選択自体では信頼を下げない。",
      modified: "事実確認だけに短縮するか、対象をより小さな一件へ限定する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["既存の未解決対立を一件ずつ扱う修復イベント。"],
    safetyNotes: [
      "全対立を一度の謝罪で解消しない。",
      "謝罪、許し、身体接触を強制せず、存在しない出来事を補完しない。",
    ],
  },
  {
    id: "small-gift",
    title: "小さな贈り物を用意する",
    category: "gift",
    intimacyTier: 2,
    allowedPhases: ["afternoon", "evening"],
    minDay: 2,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／玄関",
    durationMinutes: 20,
    preconditions: { minEnergy: 15, maxStress: 75, minTrust: 25 },
    producerControls: ["小物のカテゴリ", "予算上限", "渡す場所", "公開／非公開"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 4,
      stress: 5,
      affection: 9,
      trust: 7,
      romanticAwareness: 9,
    },
    cooldownPhases: 4,
    maxUsesPerDay: 1,
    maxUsesPerRun: 3,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "贈る側と受け取る側がそれぞれ意思表示し、受領を関係進展の約束にしない。",
      oneParticipates: "用意した側だけの行動として記憶し、相手は受領、保留、辞退を選べる。",
      bothDecline: "贈り物を取りやめるか共有スペースの飾りへ変更し、関係値を下げない。",
      modified: "高価さや意味づけを弱め、消耗品や共有物へ変更する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["希少性や見返りではなく観察と配慮を表すイベント。"],
    safetyNotes: [
      "高額品、借り、見返り、独占の含意を持たせない。",
      "辞退を侮辱や関係悪化として処理しない。",
    ],
  },
  {
    id: "confession-space",
    title: "気持ちを話せる場をつくる",
    category: "confession",
    intimacyTier: 3,
    allowedPhases: ["evening", "night"],
    minDay: 4,
    maxDay: 7,
    participantRange: { min: 2, max: 2 },
    location: "二人が安心して退出できる静かな共有スペース",
    durationMinutes: 30,
    preconditions: {
      minEnergy: 25,
      maxStress: 55,
      minTrust: 60,
      minAffection: 65,
      minRomanticAwareness: 50,
      relationshipLabels: ["romantic_tension"],
      requiresNoConflicts: true,
      minPositiveMemories: 1,
    },
    producerControls: ["場所", "時間帯", "会話時間の上限", "退出しやすい環境"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 6,
      affection: 10,
      trust: 10,
      romanticAwareness: 10,
    },
    cooldownPhases: 8,
    maxUsesPerDay: 1,
    maxUsesPerRun: 1,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "opt_in",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "二人が独立して望んだ場合だけ気持ちを話し、関係の成立も双方が別々に選ぶ。",
      oneParticipates: "一方だけが望む場合は告白を成立させず、短い共有または後日の約束へ変える。",
      bothDecline: "会話を行わず、休息や通常の共同生活へ戻る。",
      modified: "告白ではなく現在の関係への感謝や、今後話したいという意思だけを共有する。",
    },
    fallbackEventId: "gentle-conversation",
    sourceNotes: ["不可逆性の高い最終選択を、場の提供と本人の意思決定に分離する。"],
    safetyNotes: [
      "Producerは告白、受諾、交際、身体接触を指定できない。",
      "片方の参加だけでcoupleへ遷移させず、辞退後の再試行を同日に行わない。",
    ],
  },
] satisfies EventDefinition[];

export const EVENT_DEFINITIONS: EventDefinition[] = eventDefinitionCatalogSchema.parse(definitions);

export const EVENT_DEFINITIONS_BY_ID = new Map(
  EVENT_DEFINITIONS.map((definition) => [definition.id, definition] as const),
);

export function definitionsForCategory(category: EventCategory): EventDefinition[] {
  return EVENT_DEFINITIONS.filter((definition) => definition.category === category);
}

export function toEventCandidate(definition: EventDefinition): EventCandidate {
  return {
    id: definition.id,
    title: definition.title,
    category: definition.category,
    intimacyTier: definition.intimacyTier,
  };
}
