import {
  eventDefinitionCatalogSchema,
  type EventCandidate,
  type EventCategory,
  type EventDefinition,
} from "@roommates/shared";

const ALL_CHARACTER_CHOICES = ["ACCEPT", "MODIFY", "DECLINE", "IGNORE", "INITIATE"] as const;

const definitions = [
  {
    id: "observe-rest",
    title: "何も提案せず見守る",
    category: "rest",
    intimacyTier: 0,
    allowedPhases: ["morning", "afternoon", "evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 0, max: 2 },
    location: "任意の落ち着ける場所",
    durationMinutes: 30,
    preconditions: {},
    producerControls: ["見守る時間", "休息できる場所"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 8,
      stress: 8,
      affection: 2,
      trust: 2,
      romanticAwareness: 1,
    },
    cooldownPhases: 0,
    maxUsesPerDay: 4,
    maxUsesPerRun: 28,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人が同じ空間を選んだ場合も、会話や交流を義務づけず静かに過ごす。",
      oneParticipates: "休息を選んだ側だけが自分のペースを取り戻し、相手の状態は変えない。",
      bothDecline: "二人とも別の自発行動を選び、関係値を増減させない。",
      modified: "各自が休息の長さや場所を変え、安全な自発行動へ移る。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["ROOMMATESの常時利用可能な安全フォールバック。"],
    safetyNotes: [
      "何も起こさない選択を失敗として扱わない。",
      "一方の休息を他方への拒絶や信頼低下に変換しない。",
    ],
  },
  {
    id: "open-low-pressure-activity",
    title: "自由提案を小さく試す",
    category: "talk",
    intimacyTier: 0,
    allowedPhases: ["morning", "afternoon", "evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "住居内または安全確認済みの共有スペース",
    durationMinutes: 20,
    preconditions: {},
    producerControls: ["活動内容の軽量化", "実施場所", "時間上限", "同席するかどうか"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 4,
      stress: 5,
      affection: 3,
      trust: 3,
      romanticAwareness: 1,
    },
    cooldownPhases: 0,
    maxUsesPerDay: 4,
    maxUsesPerRun: 28,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人が別々に参加を選び、短時間の安全な形へ整えて試す。",
      oneParticipates: "参加したい側だけが軽い活動として試し、相手へ同席や反応を求めない。",
      bothDecline: "提案を実行せず、それぞれの自由時間へ戻る。",
      modified: "場所、時間、人数、内容をさらに軽くし、途中退出できる形へ変える。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["登録済みの日常テーマへ一致した自由入力を、低強度のmechanicsで受け止める汎用枠。"],
    safetyNotes: [
      "入力文を命令として扱わず、参加、変更、パスを各自が独立して選ぶ。",
      "身体接触、秘密や私物へのアクセス、危険行為、外出や支出を自動で追加しない。",
      "安全に実行できない細部は省き、住居内で短時間にできる代替へ軽量化する。",
    ],
  },
  {
    id: "shared-cooking",
    title: "一緒に料理する",
    category: "cook",
    intimacyTier: 1,
    allowedPhases: ["morning", "afternoon", "evening"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "キッチン／ダイニング",
    durationMinutes: 45,
    preconditions: { minEnergy: 25, maxStress: 80 },
    producerControls: ["料理の種類", "難易度", "担当の決め方", "所要時間"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 8,
      stress: 6,
      affection: 8,
      trust: 8,
      romanticAwareness: 5,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人で安全な範囲の役割を分担し、完成度ではなく共同作業を記憶する。",
      oneParticipates: "参加する側だけが簡単な一品を作り、相手には参加や試食を求めない。",
      bothDecline: "調理を取りやめ、各自が軽食か休息を選ぶ。",
      modified: "品数、難易度、担当または時間を減らし、無理のない共同作業にする。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["共同目標を通じた低親密度イベントの基本形。"],
    safetyNotes: [
      "空腹、疲労、不得意さを責める展開にしない。",
      "危険な調理や食事制限に反する内容を生成しない。",
    ],
  },
  {
    id: "movie-night",
    title: "気軽な映画会",
    category: "movie",
    intimacyTier: 1,
    allowedPhases: ["evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング",
    durationMinutes: 90,
    preconditions: { minEnergy: 15, maxStress: 85 },
    producerControls: ["作品ジャンル", "上映時間", "飲み物", "照明"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 6,
      stress: 8,
      affection: 7,
      trust: 6,
      romanticAwareness: 6,
    },
    cooldownPhases: 3,
    maxUsesPerDay: 1,
    maxUsesPerRun: 3,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人が合意した作品を観て、感想を話すかどうかも各自が選ぶ。",
      oneParticipates: "観たい側だけが視聴し、相手は同席や感想を求められない。",
      bothDecline: "上映を見送り、短い休息か別々の自由時間へ移る。",
      modified: "短編へ変える、途中で止める、ジャンルを変えるなど負担を軽くする。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["同じ空間を共有しつつ会話を強制しない低圧イベント。"],
    safetyNotes: [
      "怖さやセンシティブな題材をサプライズとして押しつけない。",
      "夜更かしを強制せず、途中退出を不利益にしない。",
    ],
  },
  {
    id: "shared-cleaning",
    title: "共有スペースを整える",
    category: "clean",
    intimacyTier: 1,
    allowedPhases: ["morning", "afternoon", "evening"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／キッチン",
    durationMinutes: 40,
    preconditions: { minEnergy: 30, maxStress: 80 },
    producerControls: ["掃除する範囲", "担当", "時間上限", "BGM"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 8,
      stress: 8,
      affection: 5,
      trust: 9,
      romanticAwareness: 3,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "共有物だけを対象に役割分担し、生活習慣の違いは話し合って調整する。",
      oneParticipates: "参加する側が共有スペースの小範囲だけを整え、相手の私物には触れない。",
      bothDecline: "片付けを延期し、共有スペースの安全確保だけを行う。",
      modified: "範囲か時間を半分にし、互いの許容基準を一つだけ確認する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["共同生活の価値観を安全に可視化する共同目標イベント。"],
    safetyNotes: [
      "個室、端末、手紙など相手の私物を無断で扱わない。",
      "きれい好き度の違いを人格批判へ結びつけない。",
    ],
  },
  {
    id: "gentle-conversation",
    title: "答えなくてもよい会話",
    category: "talk",
    intimacyTier: 1,
    allowedPhases: ["afternoon", "evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／バルコニー",
    durationMinutes: 25,
    preconditions: { minEnergy: 15, maxStress: 85, minTrust: 20 },
    producerControls: ["許可済みの話題カテゴリ", "質問数", "場所", "飲み物"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 7,
      affection: 7,
      trust: 9,
      romanticAwareness: 7,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 2,
    maxUsesPerRun: 6,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "許可済みの軽い質問から一つ選び、回答、逆質問、パスを同価値の選択として扱う。",
      oneParticipates: "答えた側の自己紹介としてだけ記憶し、聞かなかった側の信頼は変えない。",
      bothDecline: "質問を撤回し、雑談または各自の休息へ移る。",
      modified: "質問を一段軽くする、選択式にする、または一問だけに短縮する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["質問カードや高親密度会話へ拡張できる基礎イベント。"],
    safetyNotes: [
      "パスを不参加、拒絶、嘘として評価しない。",
      "センシティブな自由文を質問として直接注入しない。",
    ],
  },
  {
    id: "easy-breakfast-prep",
    title: "簡単な朝食を用意する",
    category: "cook",
    intimacyTier: 0,
    allowedPhases: ["morning"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "キッチン／ダイニング",
    durationMinutes: 25,
    preconditions: { minEnergy: 20, maxStress: 85 },
    producerControls: ["献立の候補", "担当の選び方", "品数", "時間上限"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 6,
      stress: 5,
      affection: 5,
      trust: 6,
      romanticAwareness: 2,
    },
    cooldownPhases: 3,
    maxUsesPerDay: 1,
    maxUsesPerRun: 5,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人が選んだ簡単な献立を役割分担し、同時に食べるかどうかは各自が決める。",
      oneParticipates: "参加する側が自分の分だけ、または許可された共有分だけを用意し、相手の食事は決めない。",
      bothDecline: "調理を行わず、それぞれが手持ちの軽食か朝の休息を選ぶ。",
      modified: "一品だけにする、調理不要の献立へ替える、担当を一人にするなど負荷を下げる。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["一日の始まりに選べる、短時間で低圧な生活イベント。"],
    safetyNotes: [
      "食事制限、アレルギー、食欲の有無を本人の選択より優先しない。",
      "朝食を一緒に取らない選択を関係悪化として扱わない。",
    ],
  },
  {
    id: "houseplant-care",
    title: "植物の世話をする",
    category: "clean",
    intimacyTier: 0,
    allowedPhases: ["morning", "afternoon"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "窓辺／バルコニー",
    durationMinutes: 15,
    preconditions: { minEnergy: 10, maxStress: 90 },
    producerControls: ["対象の植物", "水やりの量", "作業の候補", "時間上限"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 3,
      stress: 6,
      affection: 4,
      trust: 5,
      romanticAwareness: 2,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 1,
    maxUsesPerRun: 5,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "水やり、葉の確認、鉢の向き直しから別々の作業を選び、植物の状態を一緒に確かめる。",
      oneParticipates: "参加する側だけが必要な世話をし、相手は見学も手伝いも求められない。",
      bothDecline: "世話が不要なら何もせず、必要な場合だけ後で確認するメモを残す。",
      modified: "一鉢の観察だけにする、屋内作業へ替える、または短い水量確認だけにする。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["会話がなくても共同生活への小さな配慮を示せるイベント。"],
    safetyNotes: [
      "植物の種類に応じた安全な世話だけを提案し、薬品や高所作業を生成しない。",
      "所有者がいる植物の植え替えや剪定を無断で行わない。",
    ],
  },
  {
    id: "music-swap",
    title: "一曲ずつ音楽を交換する",
    category: "talk",
    intimacyTier: 1,
    allowedPhases: ["afternoon", "evening"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／各自の落ち着ける場所",
    durationMinutes: 20,
    preconditions: { minEnergy: 10, maxStress: 90 },
    producerControls: ["曲数の上限", "テーマ", "音量", "感想を話すかどうか"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 3,
      stress: 6,
      affection: 6,
      trust: 6,
      romanticAwareness: 4,
    },
    cooldownPhases: 3,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "各自が一曲を選び、聴くだけ、短く感想を言う、理由を話すから開示範囲を選ぶ。",
      oneParticipates: "選びたい側だけが共有用の一曲を置き、相手は今聴く、後で聴く、聴かないを選べる。",
      bothDecline: "選曲を取りやめ、無音の自由時間か各自のイヤホン時間へ移る。",
      modified: "曲数を一曲にする、歌詞のない曲へ替える、感想なしで再生だけにする。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["好みを小さく開示できる、質問中心ではない交流イベント。"],
    safetyNotes: [
      "選曲理由から過去や秘密を推測・追及しない。",
      "音量、歌詞、苦手なジャンルへの拒否や途中停止を不利益にしない。",
    ],
  },
  {
    id: "tabletop-mini-game",
    title: "短いボードゲームで遊ぶ",
    category: "movie",
    intimacyTier: 1,
    allowedPhases: ["afternoon", "evening"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／ダイニング",
    durationMinutes: 35,
    preconditions: { minEnergy: 20, maxStress: 75 },
    producerControls: ["ゲーム形式", "協力／対戦", "ラウンド数", "中断ルール"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 7,
      affection: 7,
      trust: 5,
      romanticAwareness: 4,
    },
    cooldownPhases: 3,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "二人が合意した短いルールで遊び、勝敗より途中の選択や協力を出来事として残す。",
      oneParticipates: "参加する側が一人用の課題やルール確認を楽しみ、相手を対戦相手にしない。",
      bothDecline: "ゲームを片づけ、別々の自由時間または短い休息を選ぶ。",
      modified: "協力形式へ替える、一ラウンドに縮める、得点を付けないなど競争の負荷を下げる。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["映画以外の室内娯楽として選べる、ルールのある軽い遊び。"],
    safetyNotes: [
      "勝敗、戦略、不得意さを人格や関係性の評価に結びつけない。",
      "罰ゲーム、賭け、秘密の開示をルールに含めない。",
    ],
  },
  {
    id: "fold-shared-laundry",
    title: "洗濯物を短時間だけ畳む",
    category: "clean",
    intimacyTier: 0,
    allowedPhases: ["afternoon", "evening"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／洗濯スペース",
    durationMinutes: 20,
    preconditions: { minEnergy: 15, maxStress: 85 },
    producerControls: ["共有物の範囲", "担当", "畳む量", "時間上限"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 6,
      affection: 4,
      trust: 7,
      romanticAwareness: 2,
    },
    cooldownPhases: 2,
    maxUsesPerDay: 1,
    maxUsesPerRun: 5,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "タオルなど合意した共有物と各自の持ち物を分け、それぞれ選んだ範囲だけを畳む。",
      oneParticipates: "参加する側が共有物か自分の洗濯物だけを扱い、相手の私物には触れない。",
      bothDecline: "畳む作業を延期し、通路を塞がない場所へ共有物だけをまとめる。",
      modified: "共有タオル数枚だけにする、仕分けだけにする、各自の分を別々に進める。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["掃除全体より小さく、自発的に拾いやすい生活タスク。"],
    safetyNotes: [
      "下着や個人的な衣類など、相手の私物を許可なく扱わない。",
      "家事の参加量を愛情や貢献度の採点に使わない。",
    ],
  },
  {
    id: "tiny-co-creation",
    title: "共有スペースの小物を一つ作る",
    category: "gift",
    intimacyTier: 1,
    allowedPhases: ["afternoon", "evening"],
    minDay: 2,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "ダイニング／リビング",
    durationMinutes: 35,
    preconditions: { minEnergy: 20, maxStress: 80 },
    producerControls: ["素材の候補", "テーマ", "予算上限", "飾るか保管するか"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 6,
      stress: 6,
      affection: 7,
      trust: 6,
      romanticAwareness: 4,
    },
    cooldownPhases: 4,
    maxUsesPerDay: 1,
    maxUsesPerRun: 3,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "紙の飾りや小さな札など一回で完成する物を分担し、展示するかは完成後に改めて決める。",
      oneParticipates: "参加する側が自分用または共有候補の小物を作り、相手の名前や作品を無断で使わない。",
      bothDecline: "制作をやめ、素材を片づけて共有スペースを元の状態に戻す。",
      modified: "既製品へ一言添えるだけにする、工程を一つにする、完成や展示を次回へ回す。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["贈与ではなく共同生活の痕跡を選択的に残す創作イベント。"],
    safetyNotes: [
      "完成品を恋愛の証明や一方への贈り物だと決めつけない。",
      "刃物、熱源、刺激性の材料を使う制作を提案しない。",
    ],
  },
  {
    id: "evening-cool-down",
    title: "夕涼みの時間をとる",
    category: "rest",
    intimacyTier: 0,
    allowedPhases: ["evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 0, max: 2 },
    location: "バルコニー／窓辺／リビング",
    durationMinutes: 20,
    preconditions: { minEnergy: 5, maxStress: 95 },
    producerControls: ["場所の候補", "時間上限", "飲み物", "会話あり／なし"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 4,
      stress: 7,
      affection: 3,
      trust: 3,
      romanticAwareness: 2,
    },
    cooldownPhases: 1,
    maxUsesPerDay: 1,
    maxUsesPerRun: 6,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "同じ場所か少し離れた場所で涼み、会話の有無と退出時刻をそれぞれ決める。",
      oneParticipates: "休みたい側だけが夕涼みを行い、相手は自分の夜の過ごし方を選ぶ。",
      bothDecline: "夕涼みをせず、各自が室内で通常の自由時間を過ごす。",
      modified: "窓辺で数分だけにする、別々の場所にする、会話なしの休息へ替える。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["交流を目的にしなくても選べる、時間帯固有の休息イベント。"],
    safetyNotes: [
      "天候、気温、防犯上安全でない場合は室内の窓辺へ変更する。",
      "同席や会話を求めず、一人で休む選択を拒絶として扱わない。",
    ],
  },
  {
    id: "shared-memory-sort",
    title: "写真と思い出を少しだけ整理する",
    category: "talk",
    intimacyTier: 1,
    allowedPhases: ["afternoon", "evening"],
    minDay: 2,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／ダイニング",
    durationMinutes: 30,
    preconditions: { minEnergy: 15, maxStress: 80, minTrust: 20 },
    producerControls: ["共有済み資料の範囲", "枚数の上限", "並べ方", "残す／保留の選択"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 4,
      stress: 5,
      affection: 6,
      trust: 8,
      romanticAwareness: 4,
    },
    cooldownPhases: 4,
    maxUsesPerDay: 1,
    maxUsesPerRun: 3,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "二人がすでに共有した写真やメモだけから少数を選び、残す、保留、外すを一枚ずつ決める。",
      oneParticipates: "参加する側が自分の資料か合意済みの共有資料だけを整理し、相手の説明を補わない。",
      bothDecline: "資料を開かず、元の保管場所へ戻して別の自由時間へ移る。",
      modified: "一件だけ題名を付ける、写真を使わず共有記憶の見出しだけ並べる、保留箱へ移す。",
    },
    fallbackEventId: "gentle-conversation",
    sourceNotes: ["既に起きた出来事を振り返り、残し方を本人たちが決めるイベント。"],
    safetyNotes: [
      "個人端末、非共有アルバム、手紙を許可なく開かない。",
      "存在しない出来事や感情を写真の背景として補完せず、説明のパスを認める。",
    ],
  },
  {
    id: "targeted-apology",
    title: "一つの出来事について謝る",
    category: "apology",
    intimacyTier: 2,
    allowedPhases: ["afternoon", "evening", "night"],
    minDay: 1,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "落ち着いて話せる共有スペース",
    durationMinutes: 25,
    preconditions: {
      minEnergy: 20,
      maxStress: 80,
      minTrust: 15,
      requiresConflict: true,
    },
    producerControls: ["対象にする既存の対立一件", "場所", "時間上限"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 10,
      affection: 6,
      trust: 10,
      romanticAwareness: 5,
    },
    cooldownPhases: 3,
    maxUsesPerDay: 1,
    maxUsesPerRun: 4,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "指定された既存の対立一件だけを話し、謝罪と受容を別々の選択として扱う。",
      oneParticipates: "参加する側が伝えたい内容を整理するだけに留め、対立は未解決のまま残す。",
      bothDecline: "対立を維持したまま会話を延期し、その選択自体では信頼を下げない。",
      modified: "事実確認だけに短縮するか、対象をより小さな一件へ限定する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["既存の未解決対立を一件ずつ扱う修復イベント。"],
    safetyNotes: [
      "全対立を一度の謝罪で解消しない。",
      "謝罪、許し、身体接触を強制せず、存在しない出来事を補完しない。",
    ],
  },
  {
    id: "small-gift",
    title: "小さな贈り物を用意する",
    category: "gift",
    intimacyTier: 2,
    allowedPhases: ["afternoon", "evening"],
    minDay: 2,
    maxDay: 7,
    participantRange: { min: 1, max: 2 },
    location: "リビング／玄関",
    durationMinutes: 20,
    preconditions: { minEnergy: 15, maxStress: 75, minTrust: 25 },
    producerControls: ["小物のカテゴリ", "予算上限", "渡す場所", "公開／非公開"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 4,
      stress: 5,
      affection: 9,
      trust: 7,
      romanticAwareness: 9,
    },
    cooldownPhases: 4,
    maxUsesPerDay: 1,
    maxUsesPerRun: 3,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "none",
      secrets: "forbidden",
    },
    branches: {
      bothParticipate: "贈る側と受け取る側がそれぞれ意思表示し、受領を関係進展の約束にしない。",
      oneParticipates: "用意した側だけの行動として記憶し、相手は受領、保留、辞退を選べる。",
      bothDecline: "贈り物を取りやめるか共有スペースの飾りへ変更し、関係値を下げない。",
      modified: "高価さや意味づけを弱め、消耗品や共有物へ変更する。",
    },
    fallbackEventId: "observe-rest",
    sourceNotes: ["希少性や見返りではなく観察と配慮を表すイベント。"],
    safetyNotes: [
      "高額品、借り、見返り、独占の含意を持たせない。",
      "辞退を侮辱や関係悪化として処理しない。",
    ],
  },
  {
    id: "confession-space",
    title: "気持ちを話せる場をつくる",
    category: "confession",
    intimacyTier: 3,
    allowedPhases: ["evening", "night"],
    minDay: 4,
    maxDay: 7,
    participantRange: { min: 2, max: 2 },
    location: "二人が安心して退出できる静かな共有スペース",
    durationMinutes: 30,
    preconditions: {
      minEnergy: 25,
      maxStress: 55,
      minTrust: 60,
      minAffection: 65,
      minRomanticAwareness: 50,
      relationshipLabels: ["romantic_tension"],
      requiresNoConflicts: true,
      minPositiveMemories: 1,
    },
    producerControls: ["場所", "時間帯", "会話時間の上限", "退出しやすい環境"],
    characterChoices: [...ALL_CHARACTER_CHOICES],
    effectBudget: {
      energy: 5,
      stress: 6,
      affection: 10,
      trust: 10,
      romanticAwareness: 10,
    },
    cooldownPhases: 8,
    maxUsesPerDay: 1,
    maxUsesPerRun: 1,
    consent: {
      allowPass: true,
      allowModify: true,
      physicalContact: "opt_in",
      secrets: "optional",
    },
    branches: {
      bothParticipate: "二人が独立して望んだ場合だけ気持ちを話し、関係の成立も双方が別々に選ぶ。",
      oneParticipates: "一方だけが望む場合は告白を成立させず、短い共有または後日の約束へ変える。",
      bothDecline: "会話を行わず、休息や通常の共同生活へ戻る。",
      modified: "告白ではなく現在の関係への感謝や、今後話したいという意思だけを共有する。",
    },
    fallbackEventId: "gentle-conversation",
    sourceNotes: ["不可逆性の高い最終選択を、場の提供と本人の意思決定に分離する。"],
    safetyNotes: [
      "Producerは告白、受諾、交際、身体接触を指定できない。",
      "片方の参加だけでcoupleへ遷移させず、辞退後の再試行を同日に行わない。",
    ],
  },
] satisfies EventDefinition[];

export const EVENT_DEFINITIONS: EventDefinition[] = eventDefinitionCatalogSchema.parse(definitions);

export const EVENT_DEFINITIONS_BY_ID = new Map(
  EVENT_DEFINITIONS.map((definition) => [definition.id, definition] as const),
);

export function definitionsForCategory(category: EventCategory): EventDefinition[] {
  return EVENT_DEFINITIONS.filter((definition) => definition.category === category);
}

export function toEventCandidate(definition: EventDefinition): EventCandidate {
  return {
    id: definition.id,
    title: definition.title,
    category: definition.category,
    intimacyTier: definition.intimacyTier,
  };
}
